travis:
  secure:
    BINSTAR_TOKEN: RH1M1LJwRS7GB3eF0Ot4lD2Z9oJTM9UM4DSdyg7AJY+zU38ER4yhWRMPAa9R5Vq/O8Q2DrsAOeVNDPigpp9oT3REVOkb0RWXjDhE7EdzgPotXG4Bf2LbWiBd9iVr4pMy6Hsn4/FBVqctQx/5qu3hnx7mXqNKfuRJf1140DfLMKpDrZKcNrXzdNHF8/IMA7WUQpUU1rofSx6BZRN1JKu5+Plzk7YkAWiq2QnRqDQlqzII/73EZwfrEyIs9zqOyyNpX6BhndeDj4HaCs9BY4buWQcocp+YwEVVtFvzs8TZKWCXDRzsxp9byPpfKnP2h6830BWvOsv4LEfSts3IPyI/AQwdJ29mTwAw99bRBzlsgy+hjRdf0uYpQgbXB5fJ30xTFO4B4RUjAnEbvr1xX6jo2/w6RZWh6Y4VcxYyqxUl89E/4g22fXPQfDo0kFyzSeAz6jiRaexWdTo1n2g3bQ7y/yrJHXH5kIzJIVnVtYba6TLEkTGu6ncAL3CxDTg/A9x5lDfZ7qcKsd6Dh1CI+gcX7G9UZIlWE3ITis9AC8Z3NeG/MiHP3ZLoM76sVHmPGqrllHDL+oUAitHe8vX+JSEYQqdTb/XRM45lwtlXrB41fAjnGx2+x7ExeT9isLjUega8oJeWViK5O+afU4shPXaegIJDiGrAOmeHU+VGF0p89Sw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
